In [ ]:

url_list = []
for i in range(1,8):
    url = f"https://www.1mg.com/categories/personal-care-products-18?filter=true&page={i}"
    url_list.append(url)
url_list

In [1]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import numpy as np
import seaborn as sns

# Initialize empty lists to store scraped data
Name = []    # List to store product names
Sizes = []   # List to store product sizes
MRPs = []    # List to store product maximum retail prices (MRPs)
Prices = []  # List to store product prices
URLs = []    # List to store product URLs

page = 0  # Initialize page number for pagination

# Loop to iterate through multiple pages of the website
while True:
    
    # Define headers for the HTTP request
    header={
        'Origin': 'https://www.1mg.com',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
    }
    
    # Construct the URL for the current page    

    url = "https://www.1mg.com/categories/pet-care-612?filter=true&page=" + str(page)

    # Send an HTTP GET request to the URL with the defined headers
    res = requests.get(url=url, headers=header)
    
    # Check if the page is not found (404 status)
    if res.status_code == 404:
        print("Page not found. Exiting loop.")
        break
    else:
        # Parse the HTML content of the response using BeautifulSoup
        obj = soup(res.content, 'html.parser')
        
        # Find all product boxes on the current page
        Box = obj.find_all('div', {'class': 'style__product-box___liepi'})
        
        # Loop through each product box and extract relevant information
        for i in Box:
            # Extract product name
            name = i.find('div', {'class': 'style__pro-title___2QwJy'})
            if name:
                Name.append(name.text.strip())
            else:
                Name.append(None)
            
            # Extract product size
            size = i.find('div', {'class': 'style__pack-size___2JQG7'})
            if size:
                Sizes.append(size.text.strip())
            else:
                Sizes.append(None)
            
            # Extract product MRP (maximum retail price)
            mrps = i.find('span', {'class': 'style__discount-price___25Bya'})
            if mrps:
                MRPs.append(mrps.text.replace("₹", ""))
            else:
                MRPs.append(None)
            
            # Extract product price
            price = i.find('div', {'class': 'style__price-tag___cOxYc'})
            if price:
                Prices.append(price.text.replace("₹", ""))
            else:
                Prices.append(None)
            
            # Extract product URL
            mg_url = i.find('a', {'class': 'style__product-link___UB_67'})
            if mg_url:
                b = "https://www.1mg.com" + mg_url.get('href')
                URLs.append(b)
            else:
                URLs.append(None)
        # Print progress information for the current page
        print(page,"page=>",end=" ")
    if page == 59:  # Limit to 13 pages for this example:
        break
        
    page+=1 # Move to the next page for scraping
    
    print(len(URLs),end=" ")
    print(len(Prices),end=" ")
    print(len(Sizes),end=" ")
    print(len(MRPs),end=" ")
    print(len(Name))

0 page=> 40 40 40 40 40
1 page=> 80 80 80 80 80
2 page=> 120 120 120 120 120
3 page=> 160 160 160 160 160
4 page=> 200 200 200 200 200
5 page=> 240 240 240 240 240
6 page=> 280 280 280 280 280
7 page=> 320 320 320 320 320
8 page=> 360 360 360 360 360
9 page=> 400 400 400 400 400
10 page=> 440 440 440 440 440
11 page=> 480 480 480 480 480
12 page=> 520 520 520 520 520
13 page=> 560 560 560 560 560
14 page=> 600 600 600 600 600
15 page=> 640 640 640 640 640
16 page=> 680 680 680 680 680
17 page=> 720 720 720 720 720
18 page=> 760 760 760 760 760
19 page=> 800 800 800 800 800
20 page=> 840 840 840 840 840
21 page=> 880 880 880 880 880
22 page=> 920 920 920 920 920
23 page=> 960 960 960 960 960
24 page=> 1000 1000 1000 1000 1000
25 page=> 1040 1040 1040 1040 1040
26 page=> 1080 1080 1080 1080 1080
27 page=> 1120 1120 1120 1120 1120
28 page=> 1160 1160 1160 1160 1160
29 page=> 1200 1200 1200 1200 1200
30 page=> 1240 1240 1240 1240 1240
31 page=> 1280 1280 1280 1280 1280
32 page=> 1320 1320 1320 1320 1320
33 page=> 1360 1360 1360 1360 1360
34 page=> 1400 1400 1400 1400 1400
35 page=> 1440 1440 1440 1440 1440
36 page=> 1480 1480 1480 1480 1480
37 page=> 1520 1520 1520 1520 1520
38 page=> 1560 1560 1560 1560 1560
39 page=> 1600 1600 1600 1600 1600
40 page=> 1640 1640 1640 1640 1640
41 page=> 1680 1680 1680 1680 1680
42 page=> 1720 1720 1720 1720 1720
43 page=> 1760 1760 1760 1760 1760
44 page=> 1800 1800 1800 1800 1800
45 page=> 1840 1840 1840 1840 1840
46 page=> 1880 1880 1880 1880 1880
47 page=> 1920 1920 1920 1920 1920
48 page=> 1960 1960 1960 1960 1960
49 page=> 2000 2000 2000 2000 2000
50 page=> 2040 2040 2040 2040 2040
51 page=> 2080 2080 2080 2080 2080
52 page=> 2120 2120 2120 2120 2120
53 page=> 2160 2160 2160 2160 2160
54 page=> 2200 2200 2200 2200 2200
55 page=> 2240 2240 2240 2240 2240
56 page=> 2280 2280 2280 2280 2280
57 page=> 2320 2320 2320 2320 2320
58 page=> 2360 2360 2360 2360 2360
59 page=>

In [2]:
data={"name":Name,"size_of_bottle":Sizes,"MRPs":MRPs,"selling_price":Prices,"1mg_url":URLs}

In [3]:
df = pd.DataFrame(data) # Sort the DataFrame by MRPs in descending order
df  # Sort the DataFrame by product name

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,None,MRP646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...
1,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,Discounted Price: 211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...
2,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,Discounted Price: 370,https://www.1mg.com/otc/medivet-rewive-ys-skin...
3,Aniamor Calcium Pro Powder,jar of 200 gm Powder,None,MRP650,https://www.1mg.com/otc/aniamor-calcium-pro-po...
4,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,Discounted Price: 146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...
...,...,...,...,...,...
2383,Dogsee Gigabites Cookies for Dogs Banana & Yogurt,packet of 300 gm Pet Food,None,MRP177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2384,Dogsee Gigabites Cookies for Dogs Pumpkin & Ci...,packet of 300 gm Pet Food,None,MRP177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2385,Vetlife Struvite Feline Formula,packet of 2 kg Pet Food,2590,Discounted Price: 2461,https://www.1mg.com/otc/vetlife-struvite-felin...
2386,Dogsee Chew Turmeric Himalayan Yak Chews Small...,combo pack of 3 Packs,None,MRP807,https://www.1mg.com/otc/dogsee-chew-turmeric-h...
2387,Dogsee Itch Relief Aloe Vera Shampoo,pump bottle of 200 ml Shampoo,None,MRP319.45,https://www.1mg.com/otc/dogsee-itch-relief-alo...

In [4]:
df['selling_price'] = df['selling_price'].str.replace(r'MRP\s*', '', regex=True)
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,None,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...
1,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,Discounted Price: 211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...
2,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,Discounted Price: 370,https://www.1mg.com/otc/medivet-rewive-ys-skin...
3,Aniamor Calcium Pro Powder,jar of 200 gm Powder,None,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...
4,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,Discounted Price: 146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...
...,...,...,...,...,...
2383,Dogsee Gigabites Cookies for Dogs Banana & Yogurt,packet of 300 gm Pet Food,None,177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2384,Dogsee Gigabites Cookies for Dogs Pumpkin & Ci...,packet of 300 gm Pet Food,None,177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2385,Vetlife Struvite Feline Formula,packet of 2 kg Pet Food,2590,Discounted Price: 2461,https://www.1mg.com/otc/vetlife-struvite-felin...
2386,Dogsee Chew Turmeric Himalayan Yak Chews Small...,combo pack of 3 Packs,None,807,https://www.1mg.com/otc/dogsee-chew-turmeric-h...
2387,Dogsee Itch Relief Aloe Vera Shampoo,pump bottle of 200 ml Shampoo,None,319.45,https://www.1mg.com/otc/dogsee-itch-relief-alo...

In [5]:
df['selling_price'] = df['selling_price'].str.replace(r'Discounted Price:\s*', '', regex=True)
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,None,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...
1,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...
2,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,370,https://www.1mg.com/otc/medivet-rewive-ys-skin...
3,Aniamor Calcium Pro Powder,jar of 200 gm Powder,None,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...
4,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...
5,Wagging Tails Soothing Massage Oil for Dogs & ...,box of 1 Bottle,444.03,333,https://www.1mg.com/otc/wagging-tails-soothing...
6,Bakson's Homoeopathy Distress Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...
7,Dr. Romas Homeopathy RVC SP 10 Gastro Vet,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
8,Dr. Romas Homeopathy RDC 14 Burns Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
9,Aniamor Skin & Coat Syrup,bottle of 200 ml Syrup,None,389,https://www.1mg.com/otc/aniamor-skin-coat-syru...
10,Bakson's Homoeopathy Creatinine Aid Drop for V...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-c...
11,Bakson's Homoeopathy Gentle Shampoo,bottle of 250 ml Shampoo,266.06,239,https://www.1mg.com/otc/bakson-s-homoeopathy-g...
12,Royal Canin Rottweiler Pet Food Adult,packet of 12 kg Pet Food,None,6700.42,https://www.1mg.com/otc/royal-canin-rottweiler...
13,Royal Canin Golden Retriever Pet Food Adult,packet of 3 kg Pet Food,2758.47,2621,https://www.1mg.com/otc/royal-canin-golden-ret...
14,Gnawlers Smooth & Creamy Lickable Cat Treat (4...,combo pack of 10 Packs,None,900,https://www.1mg.com/otc/gnawlers-smooth-creamy...
15,Gnawlers Yaowo Rawhide and Juice Middle,packet of 500 gm Pet Food,795,743,https://www.1mg.com/otc/gnawlers-yaowo-rawhide...
16,Dr. Romas Homeopathy RVC SP 25 Kamdhenu Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
17,JerHigh Chicken & Liver In Gravy (120gm Each),combo pack of 12 Packs,747.46,718,https://www.1mg.com/otc/jerhigh-chicken-liver-...
18,Dr. Romas Homeopathy RVC SP 2 Appito Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
19,Bakson's Homoeopathy Distemper Aid Drop for Ve...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...
20,Dr. Romas Homeopathy RVC SP 6 Bloat Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
21,Dr. Romas Homeopathy RDC 10 Pyro Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
22,Pedigree Puppy Wet Dog Food Complete and Balan...,packet of 1 Pack,None,44.49,https://www.1mg.com/otc/pedigree-puppy-wet-dog...
23,Sharrets Organic Spirulina Powder for Pets,jar of 200 gm Powder,1380,1208,https://www.1mg.com/otc/sharrets-organic-spiru...
24,Dr. Romas Homeopathy RDC 25 Liver Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
25,Bear Hugs Dog Bikkit Cookie Banana& Oats,jar of 500 gm Cookie,None,221.57,https://www.1mg.com/otc/bear-hugs-dog-bikkit-c...
26,Puppee Pet Training Pads (25 Each),box of 1 Pack,700,686,https://www.1mg.com/otc/puppee-pet-training-pa...
27,Dr. Romas Homeopathy LSD Vet 2 RVC SP 48 Tablet,bottle of 500 tablets,187.5,180,https://www.1mg.com/otc/dr.-romas-homeopathy-l...
28,Dr. Romas Homeopathy RVC SP 35 Hepto Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
29,Dr. Romas Homeopathy RDC 9 Oto Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
30,Basic Ayurveda Dashmula Taral,bottle of 1 Ltr Liquid,280,252,https://www.1mg.com/otc/basic-ayurveda-dashmul...
31,Dr. Romas Homeopathy RVC SP 24 Swastha Vardhak...,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
32,ClearKill -IMX Spot On for Dogs 10-25kg,bottle of 2.5 ml Liquid,562.5,548,https://www.1mg.com/otc/clearkill-imx-spot-on-...
33,Dr. Romas Homeopathy RVC SP 30 Cool Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
34,Gnawlers Calcium Milk Bone (12 Each),packet of 270 gm Pet Food,395,387,https://www.1mg.com/otc/gnawlers-calcium-milk-...
35,Bakson's Homoeopathy Liv Aid Drop for Veterina...,bottle of 30 ml Drop,210.9,190,https://www.1mg.com/otc/bakson-s-homoeopathy-l...
36,"Funggo LGNO Spray for Cats,Dogs & Horses",bottle of 100 ml Spray,225,219,https://www.1mg.com/otc/funggo-lgno-spray-for-...
37,ClearKill SMT Spot On for Dogs 20.1-40Kg,box of 2 ml Liquid,None,900,https://www.1mg.com/otc/clearkill-smt-spot-on-...
38,Pedigree Dentastix Daily Oral Care Dog Treat f...,box of 10 Packs,None,186.86,https://www.1mg.com/otc/pedigree-dentastix-dai...
39,Bear Hugs Dog Bikkit Cookie Chicken,jar of 500 gm Cookie,None,266.06,https://www.1mg.com/otc/bear-hugs-dog-bikkit-c...
40,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,None,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...
41,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...
42,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,370,https://www.1mg.com/otc/medivet-rewive-ys-skin...
43,Aniamor Calcium Pro Powder,jar of 200 gm Powder,None,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...
44,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...
45,Wagging Tails Soothing Massage Oil for Dogs & ...,box of 1 Bottle,444.03,333,https://www.1mg.com/otc/wagging-tails-soothing...
46,Bakson's Homoeopathy Distress Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...
47,Dr. Romas Homeopathy RVC SP 10 Gastro Vet,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
48,Dr. Romas Homeopathy RDC 14 Burns Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...
49,Aniamor Skin & Coat Syrup,bottle of 200 ml Syrup,None,389,https://www.1mg.com/otc/aniamor-skin-coat-syru...

In [6]:
df['MRPs']=df['MRPs'].fillna(df['selling_price'])
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,646.88,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...
1,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...
2,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,370,https://www.1mg.com/otc/medivet-rewive-ys-skin...
3,Aniamor Calcium Pro Powder,jar of 200 gm Powder,650,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...
4,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...
...,...,...,...,...,...
2383,Dogsee Gigabites Cookies for Dogs Banana & Yogurt,packet of 300 gm Pet Food,177.08,177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2384,Dogsee Gigabites Cookies for Dogs Pumpkin & Ci...,packet of 300 gm Pet Food,177.08,177.08,https://www.1mg.com/otc/dogsee-gigabites-cooki...
2385,Vetlife Struvite Feline Formula,packet of 2 kg Pet Food,2590,2461,https://www.1mg.com/otc/vetlife-struvite-felin...
2386,Dogsee Chew Turmeric Himalayan Yak Chews Small...,combo pack of 3 Packs,807,807,https://www.1mg.com/otc/dogsee-chew-turmeric-h...
2387,Dogsee Itch Relief Aloe Vera Shampoo,pump bottle of 200 ml Shampoo,319.45,319.45,https://www.1mg.com/otc/dogsee-itch-relief-alo...

In [7]:
df['type of product'] = df['size_of_bottle'].str.split(' ').str[-1]

In [8]:
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url,type of product
0,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,646.88,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...,Liquid
1,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...,Drop
2,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,370,https://www.1mg.com/otc/medivet-rewive-ys-skin...,Powder
3,Aniamor Calcium Pro Powder,jar of 200 gm Powder,650,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...,Powder
4,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...,Shampoo
5,Wagging Tails Soothing Massage Oil for Dogs & ...,box of 1 Bottle,444.03,333,https://www.1mg.com/otc/wagging-tails-soothing...,Bottle
6,Bakson's Homoeopathy Distress Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...,Drop
7,Dr. Romas Homeopathy RVC SP 10 Gastro Vet,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
8,Dr. Romas Homeopathy RDC 14 Burns Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Bottle
9,Aniamor Skin & Coat Syrup,bottle of 200 ml Syrup,389,389,https://www.1mg.com/otc/aniamor-skin-coat-syru...,Syrup
10,Bakson's Homoeopathy Creatinine Aid Drop for V...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-c...,Drop
11,Bakson's Homoeopathy Gentle Shampoo,bottle of 250 ml Shampoo,266.06,239,https://www.1mg.com/otc/bakson-s-homoeopathy-g...,Shampoo
12,Royal Canin Rottweiler Pet Food Adult,packet of 12 kg Pet Food,6700.42,6700.42,https://www.1mg.com/otc/royal-canin-rottweiler...,Food
13,Royal Canin Golden Retriever Pet Food Adult,packet of 3 kg Pet Food,2758.47,2621,https://www.1mg.com/otc/royal-canin-golden-ret...,Food
14,Gnawlers Smooth & Creamy Lickable Cat Treat (4...,combo pack of 10 Packs,900,900,https://www.1mg.com/otc/gnawlers-smooth-creamy...,Packs
15,Gnawlers Yaowo Rawhide and Juice Middle,packet of 500 gm Pet Food,795,743,https://www.1mg.com/otc/gnawlers-yaowo-rawhide...,Food
16,Dr. Romas Homeopathy RVC SP 25 Kamdhenu Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
17,JerHigh Chicken & Liver In Gravy (120gm Each),combo pack of 12 Packs,747.46,718,https://www.1mg.com/otc/jerhigh-chicken-liver-...,Packs
18,Dr. Romas Homeopathy RVC SP 2 Appito Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
19,Bakson's Homoeopathy Distemper Aid Drop for Ve...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...,Drop
20,Dr. Romas Homeopathy RVC SP 6 Bloat Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
21,Dr. Romas Homeopathy RDC 10 Pyro Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Bottle
22,Pedigree Puppy Wet Dog Food Complete and Balan...,packet of 1 Pack,44.49,44.49,https://www.1mg.com/otc/pedigree-puppy-wet-dog...,Pack
23,Sharrets Organic Spirulina Powder for Pets,jar of 200 gm Powder,1380,1208,https://www.1mg.com/otc/sharrets-organic-spiru...,Powder
24,Dr. Romas Homeopathy RDC 25 Liver Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Bottle
25,Bear Hugs Dog Bikkit Cookie Banana& Oats,jar of 500 gm Cookie,221.57,221.57,https://www.1mg.com/otc/bear-hugs-dog-bikkit-c...,Cookie
26,Puppee Pet Training Pads (25 Each),box of 1 Pack,700,686,https://www.1mg.com/otc/puppee-pet-training-pa...,Pack
27,Dr. Romas Homeopathy LSD Vet 2 RVC SP 48 Tablet,bottle of 500 tablets,187.5,180,https://www.1mg.com/otc/dr.-romas-homeopathy-l...,tablets
28,Dr. Romas Homeopathy RVC SP 35 Hepto Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
29,Dr. Romas Homeopathy RDC 9 Oto Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Bottle
30,Basic Ayurveda Dashmula Taral,bottle of 1 Ltr Liquid,280,252,https://www.1mg.com/otc/basic-ayurveda-dashmul...,Liquid
31,Dr. Romas Homeopathy RVC SP 24 Swastha Vardhak...,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
32,ClearKill -IMX Spot On for Dogs 10-25kg,bottle of 2.5 ml Liquid,562.5,548,https://www.1mg.com/otc/clearkill-imx-spot-on-...,Liquid
33,Dr. Romas Homeopathy RVC SP 30 Cool Vet Globules,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
34,Gnawlers Calcium Milk Bone (12 Each),packet of 270 gm Pet Food,395,387,https://www.1mg.com/otc/gnawlers-calcium-milk-...,Food
35,Bakson's Homoeopathy Liv Aid Drop for Veterina...,bottle of 30 ml Drop,210.9,190,https://www.1mg.com/otc/bakson-s-homoeopathy-l...,Drop
36,"Funggo LGNO Spray for Cats,Dogs & Horses",bottle of 100 ml Spray,225,219,https://www.1mg.com/otc/funggo-lgno-spray-for-...,Spray
37,ClearKill SMT Spot On for Dogs 20.1-40Kg,box of 2 ml Liquid,900,900,https://www.1mg.com/otc/clearkill-smt-spot-on-...,Liquid
38,Pedigree Dentastix Daily Oral Care Dog Treat f...,box of 10 Packs,186.86,186.86,https://www.1mg.com/otc/pedigree-dentastix-dai...,Packs
39,Bear Hugs Dog Bikkit Cookie Chicken,jar of 500 gm Cookie,266.06,266.06,https://www.1mg.com/otc/bear-hugs-dog-bikkit-c...,Cookie
40,ClearKill SMT Spot On for Dogs 10.1-20Kg,box of 1 ml Liquid,646.88,646.88,https://www.1mg.com/otc/clearkill-smt-spot-on-...,Liquid
41,Bakson's Homoeopathy Worm Aid Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-w...,Drop
42,Medivet Rewive-YS Skin Coat & Vision Powder,jar of 200 gm Powder,400,370,https://www.1mg.com/otc/medivet-rewive-ys-skin...,Powder
43,Aniamor Calcium Pro Powder,jar of 200 gm Powder,650,650,https://www.1mg.com/otc/aniamor-calcium-pro-po...,Powder
44,Oatem Shampoo for Dogs & Cats,bottle of 200 ml Shampoo,150,146,https://www.1mg.com/otc/oatem-shampoo-for-dogs...,Shampoo
45,Wagging Tails Soothing Massage Oil for Dogs & ...,box of 1 Bottle,444.03,333,https://www.1mg.com/otc/wagging-tails-soothing...,Bottle
46,Bakson's Homoeopathy Distress Drop for Veterin...,bottle of 30 ml Drop,234.3,211,https://www.1mg.com/otc/bakson-s-homoeopathy-d...,Drop
47,Dr. Romas Homeopathy RVC SP 10 Gastro Vet,bottle of 30 gm Globules,187.5,182,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Globules
48,Dr. Romas Homeopathy RDC 14 Burns Pet Pills,box of 30 gm Bottle,187.5,164,https://www.1mg.com/otc/dr.-romas-homeopathy-r...,Bottle
49,Aniamor Skin & Coat Syrup,bottle of 200 ml Syrup,389,389,https://www.1mg.com/otc/aniamor-skin-coat-syru...,Syrup

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2388 entries, 0 to 2387
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             2388 non-null   object
 1   size_of_bottle   2388 non-null   object
 2   MRPs             2388 non-null   object
 3   selling_price    2388 non-null   object
 4   1mg_url          2388 non-null   object
 5   type of product  2388 non-null   object
dtypes: object(6)
memory usage: 112.1+ KB

In [10]:
df['MRPs'] = pd.to_numeric(df['MRPs'], errors='coerce')
df['selling_price'] = pd.to_numeric(df['selling_price'], errors='coerce')

In [11]:
df.to_csv("C:\\Users\\MICILMEDS\\Documents\\Medi_final\\correct_data\\Category\\pet_Care.csv", index=False)  # Save the DataFrame to a CSV file