In [108]:

url_list = []
for i in range(1,8):
    url = f"https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page={i}"
    url_list.append(url)
url_list

['https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=1',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=2',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=3',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=4',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=5',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=6',
 'https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=7']

In [109]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import numpy as np
import seaborn as sns

# Initialize empty lists to store scraped data
Name = []    # List to store product names
Sizes = []   # List to store product sizes
MRPs = []    # List to store product maximum retail prices (MRPs)
Prices = []  # List to store product prices
URLs = []    # List to store product URLs

page = 0  # Initialize page number for pagination

# Loop to iterate through multiple pages of the website
while True:
    
    # Define headers for the HTTP request
    header={
        'Origin': 'https://www.1mg.com',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
    }
    
    # Construct the URL for the current page    

    url = "https://www.1mg.com/categories/summer-essentials/grooming-hygiene-3490?filter=true&page=" + str(page)

    # Send an HTTP GET request to the URL with the defined headers
    res = requests.get(url=url, headers=header)
    
    # Check if the page is not found (404 status)
    if res.status_code == 404:
        print("Page not found. Exiting loop.")
        break
    else:
        # Parse the HTML content of the response using BeautifulSoup
        obj = soup(res.content, 'html.parser')
        
        # Find all product boxes on the current page
        Box = obj.find_all('div', {'class': 'style__product-box___liepi'})
        
        # Loop through each product box and extract relevant information
        for i in Box:
            # Extract product name
            name = i.find('div', {'class': 'style__pro-title___2QwJy'})
            if name:
                Name.append(name.text.strip())
            else:
                Name.append(None)
            
            # Extract product size
            size = i.find('div', {'class': 'style__pack-size___2JQG7'})
            if size:
                Sizes.append(size.text.strip())
            else:
                Sizes.append(None)
            
            # Extract product MRP (maximum retail price)
            mrps = i.find('span', {'class': 'style__discount-price___25Bya'})
            if mrps:
                MRPs.append(mrps.text.replace("₹", ""))
            else:
                MRPs.append(None)
            
            # Extract product price
            price = i.find('div', {'class': 'style__price-tag___cOxYc'})
            if price:
                Prices.append(price.text.replace("₹", ""))
            else:
                Prices.append(None)
            
            # Extract product URL
            mg_url = i.find('a', {'class': 'style__product-link___UB_67'})
            if mg_url:
                b = "https://www.1mg.com" + mg_url.get('href')
                URLs.append(b)
            else:
                URLs.append(None)
        # Print progress information for the current page
        print(page,"page=>",end=" ")
    if page == 13:  # Limit to 13 pages for this example:
        break
        
    page+=1 # Move to the next page for scraping
    
    print(len(URLs),end=" ")
    print(len(Prices),end=" ")
    print(len(Sizes),end=" ")
    print(len(MRPs),end=" ")
    print(len(Name))

0 page=> 40 40 40 40 40
1 page=> 80 80 80 80 80
2 page=> 120 120 120 120 120
3 page=> 160 160 160 160 160
4 page=> 176 176 176 176 176
5 page=> 176 176 176 176 176
6 page=> 176 176 176 176 176
7 page=> 176 176 176 176 176
8 page=> 176 176 176 176 176
9 page=> 176 176 176 176 176
10 page=> 176 176 176 176 176
11 page=> 176 176 176 176 176
12 page=> 176 176 176 176 176
13 page=>

In [110]:
data={"name":Name,"size_of_bottle":Sizes,"MRPs":MRPs,"selling_price":Prices,"1mg_url":URLs}

In [111]:
df = pd.DataFrame(data) # Sort the DataFrame by MRPs in descending order
df  # Sort the DataFrame by product name

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,Discounted Price: 205,https://www.1mg.com/otc/bombay-shaving-company...
1,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,Discounted Price: 396,https://www.1mg.com/otc/gillette-mach-3-turbo-...
2,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,Discounted Price: 392,https://www.1mg.com/otc/vwash-expert-intimate-...
3,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,Discounted Price: 174,https://www.1mg.com/otc/vwash-plus-expert-inti...
4,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,Discounted Price: 382,https://www.1mg.com/otc/mom-world-shaverush-4-...
...,...,...,...,...,...
171,Urban Yog Hair Removal Cream Spray with Tulip ...,bottle of 200 ml Cream,850,Discounted Price: 765,https://www.1mg.com/otc/urban-yog-hair-removal...
172,Urban Yog Hair Removal Cream Spray with Rose E...,bottle of 200 ml Cream,850,Discounted Price: 765,https://www.1mg.com/otc/urban-yog-hair-removal...
173,LetsShave Pro 6 Sensitive Face & Body Shaving Kit,box of 1 Kit,1297,Discounted Price: 999,https://www.1mg.com/otc/letsshave-pro-6-sensit...
174,LetsShave Pro 4 Razor Trial Shaving Kit for Me...,box of 1 Kit,None,MRP554,https://www.1mg.com/otc/letsshave-pro-4-razor-...
175,LetsShave Pro 4 Grooming & Shaving Kit,box of 1 Kit,1152,Discounted Price: 1037,https://www.1mg.com/otc/letsshave-pro-4-groomi...

In [112]:
df['selling_price'] = df['selling_price'].str.replace(r'MRP\s*', '', regex=True)
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,Discounted Price: 205,https://www.1mg.com/otc/bombay-shaving-company...
1,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,Discounted Price: 396,https://www.1mg.com/otc/gillette-mach-3-turbo-...
2,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,Discounted Price: 392,https://www.1mg.com/otc/vwash-expert-intimate-...
3,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,Discounted Price: 174,https://www.1mg.com/otc/vwash-plus-expert-inti...
4,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,Discounted Price: 382,https://www.1mg.com/otc/mom-world-shaverush-4-...
...,...,...,...,...,...
171,Urban Yog Hair Removal Cream Spray with Tulip ...,bottle of 200 ml Cream,850,Discounted Price: 765,https://www.1mg.com/otc/urban-yog-hair-removal...
172,Urban Yog Hair Removal Cream Spray with Rose E...,bottle of 200 ml Cream,850,Discounted Price: 765,https://www.1mg.com/otc/urban-yog-hair-removal...
173,LetsShave Pro 6 Sensitive Face & Body Shaving Kit,box of 1 Kit,1297,Discounted Price: 999,https://www.1mg.com/otc/letsshave-pro-6-sensit...
174,LetsShave Pro 4 Razor Trial Shaving Kit for Me...,box of 1 Kit,None,554,https://www.1mg.com/otc/letsshave-pro-4-razor-...
175,LetsShave Pro 4 Grooming & Shaving Kit,box of 1 Kit,1152,Discounted Price: 1037,https://www.1mg.com/otc/letsshave-pro-4-groomi...

In [113]:
df['selling_price'] = df['selling_price'].str.replace(r'Discounted Price:\s*', '', regex=True)
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...
1,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,396,https://www.1mg.com/otc/gillette-mach-3-turbo-...
2,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,392,https://www.1mg.com/otc/vwash-expert-intimate-...
3,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,174,https://www.1mg.com/otc/vwash-plus-expert-inti...
4,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,382,https://www.1mg.com/otc/mom-world-shaverush-4-...
5,Vi-John Feather Touch Hair Removal Cream Haldi...,tube of 110 gm Cream,150,109,https://www.1mg.com/otc/vi-john-feather-touch-...
6,Gillette Presto Razor,packet of 5 units,100,91,https://www.1mg.com/otc/gillette-presto-razor-...
7,Gillette Guard Razor with Platinum Coated Blades,packet of 1 Unit,None,25,https://www.1mg.com/otc/gillette-guard-razor-w...
8,VWash Expert Intimate Hygiene,bottle of 100 ml Liquid,200,185,https://www.1mg.com/otc/vwash-expert-intimate-...
9,FURR by Pee Safe Body Shaving Razor,box of 1 Unit,299,150,https://www.1mg.com/otc/furr-by-pee-safe-body-...
10,Gillette Venus Smooth Razor,packet of 1 Unit,325,314,https://www.1mg.com/otc/gillette-venus-smooth-...
11,Ayouthveda Vagitone Intimate Hygiene wash with...,bottle of 180 ml Vaginal Wash,299,224,https://www.1mg.com/otc/ayouthveda-vagitone-in...
12,Oxyglow Herbals Hair Removal Cream Rose & Shea...,box of 40 gm Cream,80,56,https://www.1mg.com/otc/oxyglow-herbals-hair-r...
13,Gillette Venus Snap Hair Remover Women Razor,box of 1 Unit,None,799,https://www.1mg.com/otc/gillette-venus-snap-ha...
14,LetsShave Pro 4 Shaving Razor,box of 1 Unit,None,349,https://www.1mg.com/otc/letsshave-pro-4-shavin...
15,Uncle Tony Yellow Razor,box of 1 Unit,499,369,https://www.1mg.com/otc/uncle-tony-yellow-razo...
16,Veet Hair Removal Cream for Men | Suitable For...,tube of 50 gm Cream,175,163,https://www.1mg.com/otc/veet-hair-removal-crea...
17,Oxyglow Herbals Hair Removal Cream,box of 80 gm Cream,110,77,https://www.1mg.com/otc/oxyglow-herbals-hair-r...
18,LetsShave Body and Groin Razor for Men,box of 1 Unit,None,549,https://www.1mg.com/otc/letsshave-body-and-gro...
19,Gillette Fusion 5 Shaving Razor Blade Cartridg...,packet of 8 units,2399,2379,https://www.1mg.com/otc/gillette-fusion-5-shav...
20,C Cure Disposable Surgical Skin Blade / Prep R...,packet of 12 units,660,352,https://www.1mg.com/otc/c-cure-disposable-surg...
21,Vi-John Feather Touch Hair Removal Cream Diamo...,tube of 40 gm Cream,75,55,https://www.1mg.com/otc/vi-john-feather-touch-...
22,Bombay Shaving Company Shea Butter Hair Remova...,tube of 30 gm Cream,90,73.8,https://www.1mg.com/otc/bombay-shaving-company...
23,Mom & World Shaverush Premium Range Precision ...,box of 3 units,None,399,https://www.1mg.com/otc/mom-world-shaverush-pr...
24,Oxyglow Herbals Hair Removal Cream Lemon & Avo...,box of 40 gm Cream,80,56,https://www.1mg.com/otc/oxyglow-herbals-hair-r...
25,Sirona 5 Blade Razor Cartridge,box of 2 units,349,275,https://www.1mg.com/otc/sirona-5-blade-razor-c...
26,Gillette Fusion 5 Razor Men's Razor,packet of 1 Unit,None,425,https://www.1mg.com/otc/gillette-fusion-5-razo...
27,Gillette Mach 3 Razor (Handle + 2 Cartridge),box of 1 Unit,437,420,https://www.1mg.com/otc/gillette-mach-3-razor-...
28,Gillette Mach 3 Shaving Razor Blades,box of 6 units,890,846,https://www.1mg.com/otc/gillette-mach-3-shavin...
29,Bombay Shaving Company Bikini Razor For Women,combo pack of 2 Packs,299,245,https://www.1mg.com/otc/bombay-shaving-company...
30,Veet Hair Removal Cream for Men | Suitable For...,tube of 50 gm Cream,175,163,https://www.1mg.com/otc/veet-hair-removal-crea...
31,Gillette Venus Simply Razor for Women Buy 4 Ge...,packet of 5 units,None,399,https://www.1mg.com/otc/gillette-venus-simply-...
32,"Veet Professional Waxing Strips Kit, 8 Strips ...",box of 8 strips,120,112,https://www.1mg.com/otc/veet-professional-waxi...
33,Furr by Pee Safe Combo Pack of Advanced Nano C...,combo pack of 2 units,448,314,https://www.1mg.com/otc/furr-by-pee-safe-combo...
34,Bombay Shaving Company The Flexi Stud Razor,packet of 5 units,100,82,https://www.1mg.com/otc/bombay-shaving-company...
35,Gillette Mach 3 Shaving Razor Blades,box of 16 units,2100,1833,https://www.1mg.com/otc/gillette-mach-3-shavin...
36,Gillette Flexball Fusion 5 Proglide Razor,packet of 1 Unit,575,570,https://www.1mg.com/otc/gillette-flexball-fusi...
37,Furr Advanced Nand Coated Face Razor,box of 1 Unit,None,149,https://www.1mg.com/otc/furr-advanced-nand-coa...
38,Gillette Venus Comfortglide Razor,box of 1 Unit,375,362,https://www.1mg.com/otc/gillette-venus-comfort...
39,LetsShave Evior 6 Body Hair Removal Razor,box of 1 Unit,449,359,https://www.1mg.com/otc/letsshave-evior-6-body...
40,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...
41,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,396,https://www.1mg.com/otc/gillette-mach-3-turbo-...
42,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,392,https://www.1mg.com/otc/vwash-expert-intimate-...
43,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,174,https://www.1mg.com/otc/vwash-plus-expert-inti...
44,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,382,https://www.1mg.com/otc/mom-world-shaverush-4-...
45,Vi-John Feather Touch Hair Removal Cream Haldi...,tube of 110 gm Cream,150,109,https://www.1mg.com/otc/vi-john-feather-touch-...
46,Gillette Presto Razor,packet of 5 units,100,91,https://www.1mg.com/otc/gillette-presto-razor-...
47,Gillette Guard Razor with Platinum Coated Blades,packet of 1 Unit,None,25,https://www.1mg.com/otc/gillette-guard-razor-w...
48,VWash Expert Intimate Hygiene,bottle of 100 ml Liquid,200,185,https://www.1mg.com/otc/vwash-expert-intimate-...
49,FURR by Pee Safe Body Shaving Razor,box of 1 Unit,299,150,https://www.1mg.com/otc/furr-by-pee-safe-body-...

In [114]:
df['MRPs']=df['MRPs'].fillna(df['selling_price'])
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...
1,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,396,https://www.1mg.com/otc/gillette-mach-3-turbo-...
2,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,392,https://www.1mg.com/otc/vwash-expert-intimate-...
3,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,174,https://www.1mg.com/otc/vwash-plus-expert-inti...
4,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,382,https://www.1mg.com/otc/mom-world-shaverush-4-...
...,...,...,...,...,...
171,Urban Yog Hair Removal Cream Spray with Tulip ...,bottle of 200 ml Cream,850,765,https://www.1mg.com/otc/urban-yog-hair-removal...
172,Urban Yog Hair Removal Cream Spray with Rose E...,bottle of 200 ml Cream,850,765,https://www.1mg.com/otc/urban-yog-hair-removal...
173,LetsShave Pro 6 Sensitive Face & Body Shaving Kit,box of 1 Kit,1297,999,https://www.1mg.com/otc/letsshave-pro-6-sensit...
174,LetsShave Pro 4 Razor Trial Shaving Kit for Me...,box of 1 Kit,554,554,https://www.1mg.com/otc/letsshave-pro-4-razor-...
175,LetsShave Pro 4 Grooming & Shaving Kit,box of 1 Kit,1152,1037,https://www.1mg.com/otc/letsshave-pro-4-groomi...

In [115]:
df['type of product'] = df['size_of_bottle'].str.split(' ').str[-1]

In [116]:
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url,type of product
0,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...,units
1,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,396,https://www.1mg.com/otc/gillette-mach-3-turbo-...,Unit
2,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,392,https://www.1mg.com/otc/vwash-expert-intimate-...,Liquid
3,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,174,https://www.1mg.com/otc/vwash-plus-expert-inti...,Liquid
4,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,382,https://www.1mg.com/otc/mom-world-shaverush-4-...,Unit
5,Vi-John Feather Touch Hair Removal Cream Haldi...,tube of 110 gm Cream,150,109,https://www.1mg.com/otc/vi-john-feather-touch-...,Cream
6,Gillette Presto Razor,packet of 5 units,100,91,https://www.1mg.com/otc/gillette-presto-razor-...,units
7,Gillette Guard Razor with Platinum Coated Blades,packet of 1 Unit,25,25,https://www.1mg.com/otc/gillette-guard-razor-w...,Unit
8,VWash Expert Intimate Hygiene,bottle of 100 ml Liquid,200,185,https://www.1mg.com/otc/vwash-expert-intimate-...,Liquid
9,FURR by Pee Safe Body Shaving Razor,box of 1 Unit,299,150,https://www.1mg.com/otc/furr-by-pee-safe-body-...,Unit
10,Gillette Venus Smooth Razor,packet of 1 Unit,325,314,https://www.1mg.com/otc/gillette-venus-smooth-...,Unit
11,Ayouthveda Vagitone Intimate Hygiene wash with...,bottle of 180 ml Vaginal Wash,299,224,https://www.1mg.com/otc/ayouthveda-vagitone-in...,Wash
12,Oxyglow Herbals Hair Removal Cream Rose & Shea...,box of 40 gm Cream,80,56,https://www.1mg.com/otc/oxyglow-herbals-hair-r...,Cream
13,Gillette Venus Snap Hair Remover Women Razor,box of 1 Unit,799,799,https://www.1mg.com/otc/gillette-venus-snap-ha...,Unit
14,LetsShave Pro 4 Shaving Razor,box of 1 Unit,349,349,https://www.1mg.com/otc/letsshave-pro-4-shavin...,Unit
15,Uncle Tony Yellow Razor,box of 1 Unit,499,369,https://www.1mg.com/otc/uncle-tony-yellow-razo...,Unit
16,Veet Hair Removal Cream for Men | Suitable For...,tube of 50 gm Cream,175,163,https://www.1mg.com/otc/veet-hair-removal-crea...,Cream
17,Oxyglow Herbals Hair Removal Cream,box of 80 gm Cream,110,77,https://www.1mg.com/otc/oxyglow-herbals-hair-r...,Cream
18,LetsShave Body and Groin Razor for Men,box of 1 Unit,549,549,https://www.1mg.com/otc/letsshave-body-and-gro...,Unit
19,Gillette Fusion 5 Shaving Razor Blade Cartridg...,packet of 8 units,2399,2379,https://www.1mg.com/otc/gillette-fusion-5-shav...,units
20,C Cure Disposable Surgical Skin Blade / Prep R...,packet of 12 units,660,352,https://www.1mg.com/otc/c-cure-disposable-surg...,units
21,Vi-John Feather Touch Hair Removal Cream Diamo...,tube of 40 gm Cream,75,55,https://www.1mg.com/otc/vi-john-feather-touch-...,Cream
22,Bombay Shaving Company Shea Butter Hair Remova...,tube of 30 gm Cream,90,73.8,https://www.1mg.com/otc/bombay-shaving-company...,Cream
23,Mom & World Shaverush Premium Range Precision ...,box of 3 units,399,399,https://www.1mg.com/otc/mom-world-shaverush-pr...,units
24,Oxyglow Herbals Hair Removal Cream Lemon & Avo...,box of 40 gm Cream,80,56,https://www.1mg.com/otc/oxyglow-herbals-hair-r...,Cream
25,Sirona 5 Blade Razor Cartridge,box of 2 units,349,275,https://www.1mg.com/otc/sirona-5-blade-razor-c...,units
26,Gillette Fusion 5 Razor Men's Razor,packet of 1 Unit,425,425,https://www.1mg.com/otc/gillette-fusion-5-razo...,Unit
27,Gillette Mach 3 Razor (Handle + 2 Cartridge),box of 1 Unit,437,420,https://www.1mg.com/otc/gillette-mach-3-razor-...,Unit
28,Gillette Mach 3 Shaving Razor Blades,box of 6 units,890,846,https://www.1mg.com/otc/gillette-mach-3-shavin...,units
29,Bombay Shaving Company Bikini Razor For Women,combo pack of 2 Packs,299,245,https://www.1mg.com/otc/bombay-shaving-company...,Packs
30,Veet Hair Removal Cream for Men | Suitable For...,tube of 50 gm Cream,175,163,https://www.1mg.com/otc/veet-hair-removal-crea...,Cream
31,Gillette Venus Simply Razor for Women Buy 4 Ge...,packet of 5 units,399,399,https://www.1mg.com/otc/gillette-venus-simply-...,units
32,"Veet Professional Waxing Strips Kit, 8 Strips ...",box of 8 strips,120,112,https://www.1mg.com/otc/veet-professional-waxi...,strips
33,Furr by Pee Safe Combo Pack of Advanced Nano C...,combo pack of 2 units,448,314,https://www.1mg.com/otc/furr-by-pee-safe-combo...,units
34,Bombay Shaving Company The Flexi Stud Razor,packet of 5 units,100,82,https://www.1mg.com/otc/bombay-shaving-company...,units
35,Gillette Mach 3 Shaving Razor Blades,box of 16 units,2100,1833,https://www.1mg.com/otc/gillette-mach-3-shavin...,units
36,Gillette Flexball Fusion 5 Proglide Razor,packet of 1 Unit,575,570,https://www.1mg.com/otc/gillette-flexball-fusi...,Unit
37,Furr Advanced Nand Coated Face Razor,box of 1 Unit,149,149,https://www.1mg.com/otc/furr-advanced-nand-coa...,Unit
38,Gillette Venus Comfortglide Razor,box of 1 Unit,375,362,https://www.1mg.com/otc/gillette-venus-comfort...,Unit
39,LetsShave Evior 6 Body Hair Removal Razor,box of 1 Unit,449,359,https://www.1mg.com/otc/letsshave-evior-6-body...,Unit
40,Bombay Shaving Company Flexi Body Razor,combo pack of 3 units,250,205,https://www.1mg.com/otc/bombay-shaving-company...,units
41,Gillette Mach 3 Turbo Razor,box of 1 Unit,399,396,https://www.1mg.com/otc/gillette-mach-3-turbo-...,Unit
42,VWash Expert Intimate Hygiene,bottle of 200 ml Liquid,410,392,https://www.1mg.com/otc/vwash-expert-intimate-...,Liquid
43,VWash Plus Expert Intimate Hygiene,bottle of 100 ml Liquid,200,174,https://www.1mg.com/otc/vwash-plus-expert-inti...,Liquid
44,Mom & World Shaverush 4 Blade Full Body Razor,box of 1 Unit,399,382,https://www.1mg.com/otc/mom-world-shaverush-4-...,Unit
45,Vi-John Feather Touch Hair Removal Cream Haldi...,tube of 110 gm Cream,150,109,https://www.1mg.com/otc/vi-john-feather-touch-...,Cream
46,Gillette Presto Razor,packet of 5 units,100,91,https://www.1mg.com/otc/gillette-presto-razor-...,units
47,Gillette Guard Razor with Platinum Coated Blades,packet of 1 Unit,25,25,https://www.1mg.com/otc/gillette-guard-razor-w...,Unit
48,VWash Expert Intimate Hygiene,bottle of 100 ml Liquid,200,185,https://www.1mg.com/otc/vwash-expert-intimate-...,Liquid
49,FURR by Pee Safe Body Shaving Razor,box of 1 Unit,299,150,https://www.1mg.com/otc/furr-by-pee-safe-body-...,Unit

In [117]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176 entries, 0 to 175
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             176 non-null    object
 1   size_of_bottle   176 non-null    object
 2   MRPs             176 non-null    object
 3   selling_price    176 non-null    object
 4   1mg_url          176 non-null    object
 5   type of product  176 non-null    object
dtypes: object(6)
memory usage: 8.4+ KB

In [118]:
df['MRPs'] = pd.to_numeric(df['MRPs'], errors='coerce')
df['selling_price'] = pd.to_numeric(df['selling_price'], errors='coerce')

In [119]:
df.to_csv("C:\\Users\\MICILMEDS\\Documents\\Medi_final\\correct_data\\Category\\smart_Watches_Rings.csv", index=False)  # Save the DataFrame to a CSV file