In [74]:

url_list = []
for i in range(1,8):
    url = f"https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber={i}"
    url_list.append(url)
url_list

['https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=1',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=2',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=3',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=4',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=5',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=6',
 'https://www.1mg.com/categories/homeopathy/homeopathy-medicines-106?filter=true&pageNumber=7']

In [75]:
import requests
from bs4 import BeautifulSoup as soup
import pandas as pd
import numpy as np
import seaborn as sns

# Initialize empty lists to store scraped data
Name = []    # List to store product names
Sizes = []   # List to store product sizes
MRPs = []    # List to store product maximum retail prices (MRPs)
Prices = []  # List to store product prices
URLs = []    # List to store product URLs

page = 0  # Initialize page number for pagination

# Loop to iterate through multiple pages of the website
while True:
    
    # Define headers for the HTTP request
    header={
        'Origin': 'https://www.1mg.com',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'
    }
    
    # Construct the URL for the current page    

    url = "https://www.1mg.com/categories/anti-pollution/vaporizers-nebulizers-186?filter=true&page=" + str(page)

    # Send an HTTP GET request to the URL with the defined headers
    res = requests.get(url=url, headers=header)
    
    # Check if the page is not found (404 status)
    if res.status_code == 404:
        print("Page not found. Exiting loop.")
        break
    else:
        # Parse the HTML content of the response using BeautifulSoup
        obj = soup(res.content, 'html.parser')
        
        # Find all product boxes on the current page
        Box = obj.find_all('div', {'class': 'style__product-box___liepi'})
        
        # Loop through each product box and extract relevant information
        for i in Box:
            # Extract product name
            name = i.find('div', {'class': 'style__pro-title___2QwJy'})
            if name:
                Name.append(name.text.strip())
            else:
                Name.append(None)
            
            # Extract product size
            size = i.find('div', {'class': 'style__pack-size___2JQG7'})
            if size:
                Sizes.append(size.text.strip())
            else:
                Sizes.append(None)
            
            # Extract product MRP (maximum retail price)
            mrps = i.find('span', {'class': 'style__discount-price___25Bya'})
            if mrps:
                MRPs.append(mrps.text.replace("₹", ""))
            else:
                MRPs.append(None)
            
            # Extract product price
            price = i.find('div', {'class': 'style__price-tag___cOxYc'})
            if price:
                Prices.append(price.text.replace("₹", ""))
            else:
                Prices.append(None)
            
            # Extract product URL
            mg_url = i.find('a', {'class': 'style__product-link___UB_67'})
            if mg_url:
                b = "https://www.1mg.com" + mg_url.get('href')
                URLs.append(b)
            else:
                URLs.append(None)
        # Print progress information for the current page
        print(page,"page=>",end=" ")
    if page == 11 :
        break
        
    page+=1 # Move to the next page for scraping
    
    print(len(URLs),end=" ")
    print(len(Prices),end=" ")
    print(len(Sizes),end=" ")
    print(len(MRPs),end=" ")
    print(len(Name))

0 page=> 41 41 41 41 41
1 page=> 82 82 82 82 82
2 page=> 123 123 123 123 123
3 page=> 164 164 164 164 164
4 page=> 205 205 205 205 205
5 page=> 245 245 245 245 245
6 page=> 285 285 285 285 285
7 page=> 325 325 325 325 325
8 page=> 365 365 365 365 365
9 page=> 405 405 405 405 405
10 page=> 438 438 438 438 438
11 page=>

In [76]:
Box

[]

In [77]:
data={"name":Name,"size_of_bottle":Sizes,"MRPs":MRPs,"selling_price":Prices,"1mg_url":URLs}

In [78]:
df = pd.DataFrame(data) # Sort the DataFrame by MRPs in descending order
df  # Sort the DataFrame by product name

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,Discounted Price: 295,https://www.1mg.com/otc/asbob-healthcare-3-in-...
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,Discounted Price: 1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,Discounted Price: 1482,https://www.1mg.com/otc/compact-nebulizer-with...
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,Discounted Price: 472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,Discounted Price: 1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
...,...,...,...,...,...
433,Extra Care EC 20 Nebulizer Compressor System,box of 1 Unit,1750,Discounted Price: 892,https://www.1mg.com/otc/extra-care-ec-20-nebul...
434,Amkay Nebulizer Mask with Anti-spill jar | Tra...,box of 1 Unit,549,Discounted Price: 428,https://www.1mg.com/otc/amkay-nebulizer-mask-w...
435,Smart Care NB04 Nebuliser with Piston Compressor,box of 1 Nebuliser,2500,Discounted Price: 2203,https://www.1mg.com/otc/smart-care-nb04-nebuli...
436,Vrevive Respiratory Nebuliser,box of 1 Nebuliser,2390,Discounted Price: 1890,https://www.1mg.com/otc/vrevive-respiratory-ne...
437,Control D Handle Nebulizer for Child and Adult,box of 1 Unit,1649,Discounted Price: 1237,https://www.1mg.com/otc/control-d-handle-nebul...

In [79]:
df['selling_price'] = df['selling_price'].str.replace(r'MRP\s*', '', regex=True)
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,Discounted Price: 295,https://www.1mg.com/otc/asbob-healthcare-3-in-...
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,Discounted Price: 1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,Discounted Price: 1482,https://www.1mg.com/otc/compact-nebulizer-with...
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,Discounted Price: 472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,Discounted Price: 1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
...,...,...,...,...,...
433,Extra Care EC 20 Nebulizer Compressor System,box of 1 Unit,1750,Discounted Price: 892,https://www.1mg.com/otc/extra-care-ec-20-nebul...
434,Amkay Nebulizer Mask with Anti-spill jar | Tra...,box of 1 Unit,549,Discounted Price: 428,https://www.1mg.com/otc/amkay-nebulizer-mask-w...
435,Smart Care NB04 Nebuliser with Piston Compressor,box of 1 Nebuliser,2500,Discounted Price: 2203,https://www.1mg.com/otc/smart-care-nb04-nebuli...
436,Vrevive Respiratory Nebuliser,box of 1 Nebuliser,2390,Discounted Price: 1890,https://www.1mg.com/otc/vrevive-respiratory-ne...
437,Control D Handle Nebulizer for Child and Adult,box of 1 Unit,1649,Discounted Price: 1237,https://www.1mg.com/otc/control-d-handle-nebul...

In [80]:
df['selling_price'] = df['selling_price'].str.replace(r'Discounted Price:\s*', '', regex=True)
df.head(50)

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,295,https://www.1mg.com/otc/asbob-healthcare-3-in-...
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,1482,https://www.1mg.com/otc/compact-nebulizer-with...
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
5,Dr Morepen VP 06 Breathe Free Vaporizer,box of 1 Unit,450,225,https://www.1mg.com/otc/dr-morepen-vp-06-breat...
6,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,None,1386,https://www.1mg.com/otc/compact-nebulizer-with...
7,Sara+Care NEB 105 Nebulizer Kit with Aerosol Mask,box of 1 Kit,250,243,https://www.1mg.com/otc/sara-care-neb-105-nebu...
8,Ambitech Child Nebulizer Mask with Air Tube,box of 1 Unit,399,207,https://www.1mg.com/otc/ambitech-child-nebuliz...
9,K-Life Neb 102B Portable Piston Compressor Neb...,box of 1 Nebuliser,3499,1717,https://www.1mg.com/otc/k-life-neb-102b-portab...
10,Sahyog Wellness MY 520 Portable Ultrasonic Neb...,box of 1 Unit,1499,1216,https://www.1mg.com/otc/sahyog-wellness-my-520...
11,"Sahyog Wellness Sturdy Vaporizer for Nose, Fac...",box of 1 Unit,899,400,https://www.1mg.com/otc/sahyog-wellness-sturdy...
12,Crescent Delux Facial Steamer Vaporizer for Co...,box of 1 Unit,None,499,https://www.1mg.com/otc/crescent-delux-facial-...
13,Sahyog Wellness Piston Compressor Nebulizer,box of 1 Unit,1499,1050,https://www.1mg.com/otc/sahyog-wellness-piston...
14,Ambitech Portable Compressor Nebulizer Machine,box of 1 Unit,1799,1657,https://www.1mg.com/otc/ambitech-portable-comp...
15,"Dr. Korpet 3 in 1 Steamer, Vaporizers, Steam I...",box of 1 Unit,620,280,https://www.1mg.com/otc/dr.-korpet-3-in-1-stea...
16,Crescent Delux Facial Steamer Vaporizer for Co...,box of 1 Unit,None,499,https://www.1mg.com/otc/crescent-delux-facial-...
17,Accusure Accusure Nebulizer-JL,box of 1 Unit,None,1925,https://www.1mg.com/otc/accusure-accusure-nebu...
18,Crescent Delux Facial Steamer Vaporizer for Co...,box of 1 Unit,None,499,https://www.1mg.com/otc/crescent-delux-facial-...
19,Sara+Care VAP 102 Vaporizer,box of 1 Unit,799,411,https://www.1mg.com/otc/sara-care-vap-102-vapo...
20,MCP Healthcare Medi Mist Compressor Nebuliser ...,box of 1 Unit,2999,2252,https://www.1mg.com/otc/mcp-healthcare-medi-mi...
21,Sara+Care NEB 108 Ultrasonic Mesh Nebuliser,box of 1 Unit,2285,1288,https://www.1mg.com/otc/sara-care-neb-108-ultr...
22,Beurer IH 18 Nebuliser White,box of 1 Unit,2615,1781,https://www.1mg.com/otc/beurer-ih-18-nebuliser...
23,AccuSure Nebulizer-UL,box of 1 Unit,None,1599,https://www.1mg.com/otc/accusure-nebulizer-ul-...
24,Dr. Gene Accusure Nebuliser SL,box of 1 Unit,1330,1225,https://www.1mg.com/otc/dr.-gene-accusure-nebu...
25,Romsons Angel Compressor System Nebulizer,box of 1 Nebuliser,1950,972,https://www.1mg.com/otc/romsons-angel-compress...
26,Fidelis Healthcare Facial Steam Vaporizer Machine,box of 1 Unit,650,319,https://www.1mg.com/otc/fidelis-healthcare-fac...
27,K-Life Neb 107 Portable Piston Compressor Nebu...,box of 1 Nebuliser,1799,1205,https://www.1mg.com/otc/k-life-neb-107-portabl...
28,Dominion Care Nebulizer Adult Kit,box of 1 Kit,350,133,https://www.1mg.com/otc/dominion-care-nebulize...
29,Medtech Handyneb Classic Nebuliser,box of 1 Unit,1615,1601,https://www.1mg.com/otc/medtech-handyneb-class...
30,Sketch All-In-One Steam Vaporizer,box of 1 Unit,599,300,https://www.1mg.com/otc/sketch-all-in-one-stea...
31,Crescent Economy Facial Steamer Vaporizer for ...,box of 1 Unit,299,199,https://www.1mg.com/otc/crescent-economy-facia...
32,Healthtokri 3 in 1 Facial Sauna Steamer/Vapori...,box of 1 Unit,None,399,https://www.1mg.com/otc/healthtokri-3-in-1-fac...
33,K-Life 102 Nebuliser Piston Compressor with Th...,box of 1 Unit,2999,2054,https://www.1mg.com/otc/k-life-102-nebuliser-p...
34,Crescent Delux Facial Steamer Vaporizer for Co...,box of 1 Unit,499,389,https://www.1mg.com/otc/crescent-delux-facial-...
35,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,285,https://www.1mg.com/otc/asbob-healthcare-3-in-...
36,K-Life Neb 101 Nebulizer Compressor System White,box of 1 Nebuliser,2499,1617,https://www.1mg.com/otc/k-life-neb-101-nebuliz...
37,Medtech Handyneb Gold Nebuliser,box of 1 Nebuliser,None,1667,https://www.1mg.com/otc/medtech-handyneb-gold-...
38,Romsons Microgen Compressor Nebulizer,box of 1 Nebuliser,1716,1054,https://www.1mg.com/otc/romsons-microgen-compr...
39,Crescent Facial Steamer Vaporizer for Cold and...,box of 1 Unit,299,199,https://www.1mg.com/otc/crescent-facial-steame...
40,Crescent Delux Facial Steamer Vaporizer for Co...,box of 1 Unit,499,350,https://www.1mg.com/otc/crescent-delux-facial-...
41,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,295,https://www.1mg.com/otc/asbob-healthcare-3-in-...
42,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
43,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,1482,https://www.1mg.com/otc/compact-nebulizer-with...
44,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...
45,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
46,Dr Morepen VP 06 Breathe Free Vaporizer,box of 1 Unit,450,225,https://www.1mg.com/otc/dr-morepen-vp-06-breat...
47,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,None,1386,https://www.1mg.com/otc/compact-nebulizer-with...
48,Sara+Care NEB 105 Nebulizer Kit with Aerosol Mask,box of 1 Kit,250,243,https://www.1mg.com/otc/sara-care-neb-105-nebu...
49,Ambitech Child Nebulizer Mask with Air Tube,box of 1 Unit,399,207,https://www.1mg.com/otc/ambitech-child-nebuliz...

In [81]:
df['MRPs']=df['MRPs'].fillna(df['selling_price'])
df

,name,size_of_bottle,MRPs,selling_price,1mg_url
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,295,https://www.1mg.com/otc/asbob-healthcare-3-in-...
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,1482,https://www.1mg.com/otc/compact-nebulizer-with...
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...
...,...,...,...,...,...
433,Extra Care EC 20 Nebulizer Compressor System,box of 1 Unit,1750,892,https://www.1mg.com/otc/extra-care-ec-20-nebul...
434,Amkay Nebulizer Mask with Anti-spill jar | Tra...,box of 1 Unit,549,428,https://www.1mg.com/otc/amkay-nebulizer-mask-w...
435,Smart Care NB04 Nebuliser with Piston Compressor,box of 1 Nebuliser,2500,2203,https://www.1mg.com/otc/smart-care-nb04-nebuli...
436,Vrevive Respiratory Nebuliser,box of 1 Nebuliser,2390,1890,https://www.1mg.com/otc/vrevive-respiratory-ne...
437,Control D Handle Nebulizer for Child and Adult,box of 1 Unit,1649,1237,https://www.1mg.com/otc/control-d-handle-nebul...

In [82]:
df['type of product'] = df['size_of_bottle'].str.split(' ').str[-1]

In [83]:
df

,name,size_of_bottle,MRPs,selling_price,1mg_url,type of product
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,295,https://www.1mg.com/otc/asbob-healthcare-3-in-...,Unit
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...,Inhaler
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,1482,https://www.1mg.com/otc/compact-nebulizer-with...,Unit
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...,Unit
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...,Inhaler
...,...,...,...,...,...,...
433,Extra Care EC 20 Nebulizer Compressor System,box of 1 Unit,1750,892,https://www.1mg.com/otc/extra-care-ec-20-nebul...,Unit
434,Amkay Nebulizer Mask with Anti-spill jar | Tra...,box of 1 Unit,549,428,https://www.1mg.com/otc/amkay-nebulizer-mask-w...,Unit
435,Smart Care NB04 Nebuliser with Piston Compressor,box of 1 Nebuliser,2500,2203,https://www.1mg.com/otc/smart-care-nb04-nebuli...,Nebuliser
436,Vrevive Respiratory Nebuliser,box of 1 Nebuliser,2390,1890,https://www.1mg.com/otc/vrevive-respiratory-ne...,Nebuliser
437,Control D Handle Nebulizer for Child and Adult,box of 1 Unit,1649,1237,https://www.1mg.com/otc/control-d-handle-nebul...,Unit

In [84]:
df

,name,size_of_bottle,MRPs,selling_price,1mg_url,type of product
0,"Asbob Healthcare 3 in 1 Vaporizers, Steam Inha...",box of 1 Unit,650,295,https://www.1mg.com/otc/asbob-healthcare-3-in-...,Unit
1,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...,Inhaler
2,Compact Nebulizer with Adjustable Flow Rate | ...,box of 1 Unit,1645,1482,https://www.1mg.com/otc/compact-nebulizer-with...,Unit
3,Healthgenie 3 in 1 Steam Sauna Vaporizer Super...,box of 1 Unit,549,472,https://www.1mg.com/otc/healthgenie-3-in-1-ste...,Unit
4,Medtech VAP 100 Handyvap Steam Inhaler,box of 1 Inhaler,3099,1902,https://www.1mg.com/otc/medtech-vap-100-handyv...,Inhaler
...,...,...,...,...,...,...
433,Extra Care EC 20 Nebulizer Compressor System,box of 1 Unit,1750,892,https://www.1mg.com/otc/extra-care-ec-20-nebul...,Unit
434,Amkay Nebulizer Mask with Anti-spill jar | Tra...,box of 1 Unit,549,428,https://www.1mg.com/otc/amkay-nebulizer-mask-w...,Unit
435,Smart Care NB04 Nebuliser with Piston Compressor,box of 1 Nebuliser,2500,2203,https://www.1mg.com/otc/smart-care-nb04-nebuli...,Nebuliser
436,Vrevive Respiratory Nebuliser,box of 1 Nebuliser,2390,1890,https://www.1mg.com/otc/vrevive-respiratory-ne...,Nebuliser
437,Control D Handle Nebulizer for Child and Adult,box of 1 Unit,1649,1237,https://www.1mg.com/otc/control-d-handle-nebul...,Unit

In [85]:
df.to_csv("C:\\Users\\MICILMEDS\\Documents\\Medi_final\\correct_data\\Category\\Nabulizers.csv", index=False)  # Save the DataFrame to a CSV file